### ISSUE TITLE
FAQ Page error 

### ISSUE THREAD

**Issue by lwoodruff22** [MastekApps/FaqPage#1]
I have created several FAQ sets and added questions under each.  For some reason, I have some questions appearing under multiple sets from the UI perspective.  When I go to edit the sets, the questions are all displaying in the correct locations, so there is nothing I can change.  Any ideas?
thanks!

**Comment by s-KaiNet** [comment]
I think this issue UI \ markup related. Is it possible to see some screenshots?

**Comment by lwoodruff22** [comment]
Thanks for the quick reply-  here are screenshots:
[cid:image001.jpg@01D189BD.7BCECDF0]
But here is what is displayed in the UI
[cid:image002.jpg@01D189BD.7BCECDF0]

The noted items are also displayed correctly under the Database section

**Comment by s-KaiNet** [comment]
It seems screens didn't paste correctly from mail reply.

**Comment by lwoodruff22** [comment]
trying again -
![faq1](https://cloud.githubusercontent.com/assets/18147802/14125985/fc4d7802-f5c2-11e5-80d4-970d37eace3e.jpg)
![faq2](https://cloud.githubusercontent.com/assets/18147802/14125988/00d4ba3e-f5c3-11e5-93d5-1ecb6f7a7dc0.jpg)

**Comment by s-KaiNet** [comment]
That's strange. For me it looks like the site on the first screen is not direct child for the site, where FAQ Page web part created. Can you please check that?

**Comment by lwoodruff22** [comment]
I checked that the FAQ app was added to the Knowledge base site and that is where I am opening the FAQs for editing.  The questions still appear to be in the correct categories from the FAQ app, but not in the UI still. 
![faq3](https://cloud.githubusercontent.com/assets/18147802/14147196/52ae0158-f64f-11e5-82ba-c595411693d5.PNG)
![faq4](https://cloud.githubusercontent.com/assets/18147802/14147200/5658ec32-f64f-11e5-9610-df3151d96cec.PNG)

**Comment by s-KaiNet** [comment]
Ok, that's looks really strange for me. 
Can you please write a message to my email (you can find it under "Contact Developer") section. I don't want to share email here. And we schedule a meeting so I can take a closer look what is happening.   
Looks good for you?

**Comment by s-KaiNet** [comment]
bug: when FAQ set name contains other FAQ set name, for example `Data` and `Database` - FAQ web part doesn't display answers correctly.

**Comment by lwoodruff22** [comment]
Renaming the FAQ Set resolved the issue.

**Comment by s-KaiNet** [comment]
@lwoodruff22   
just want to let you know, that the version 1.1.1.0 which fix this issue is available in the app store.
