### ISSUE TITLE
Export the faq

### ISSUE THREAD

**Issue by ykyuen** [MastekApps/FaqPage#10]
Thanks creating this project. it is useful.

I wonder if there is anyway which i could export all faq as a backup? actually where does the faq stored?

Thanks.

**Comment by ralf-ak** [comment]
Hi,
Is there any update on this?
Thanks

**Comment by s-KaiNet** [comment]
Hello, 

Sorry, but I'm not planning to update this app anymore. It's provided as-is, free of charge and open-sourced. You can modify it according to your needs.
