### ISSUE TITLE
Cannot access permissions / need to share my FAQ page in other team

### ISSUE THREAD

**Issue by hichamzeh** [MastekApps/FaqPage#19]
My question is related to FAQ Page application :
I have a page in our private team site (spo) where i am using the FAQ Page app and it is working very well .
Now i am trying to share this page with users outside the private team , but within the same organisation . I have set the permissions for the page as : Everyone except external users , but it didnt work . Users can open the link shared , but without being able to view the content , which is rendered by the FAQ app .
Is is because those users dont have permissions for the FAQ app? Any ideas? Please help
Thanks in advance

**Comment by s-KaiNet** [comment]
Hi, 

yes, FAQ app has a separate sub-site. You should add permisions for those users for the whole site, otherwise they wil not see the content.

**Comment by hichamzeh** [comment]
Thanks !
