### ISSUE TITLE
FAQ installer for sharepoint 2013 on premise

### ISSUE THREAD

**Issue by popeye669** [MastekApps/FaqPage#2]
Hello Sergei,We are interested in installing the FAQ page app, however we cant  do it using the Microsoft app store. Is it possible to get the installer for it for sharepoint 2013 on premise so we can install it without going thru the MS store? Thanks for your help and look forward to hearing from you. Pete

**Comment by s-KaiNet** [comment]
Hi, Pete, 
yes this is possible. I will do a release later today and let you know how to install it.

**Comment by s-KaiNet** [comment]
@popeye669  
I've added release for latest 1.1.2.0 version. Use [this page](https://github.com/MastekApps/FaqPage/releases/tag/1.1.2.0) to download `FaqPage.zip` file, unpack and install `FaqPage.app` in your farm

**Comment by popeye669** [comment]
Hi Sergi,

Thanks for doing that, are there any instructions that you can point me to that walks me thru installing the app file  in sharepoint ?

Thanks,
Peter Kaldani

**Comment by s-KaiNet** [comment]
You can follow official instruction from MS, here is the list I found: 
- [Use the App Catalog to make custom business apps available for your SharePoint Online environment](https://support.office.com/en-us/article/Use-the-App-Catalog-to-make-custom-business-apps-available-for-your-SharePoint-Online-environment-0b6ab336-8b83-423f-a06b-bcc52861cba0)
- [Install and manage apps for SharePoint 2013](https://technet.microsoft.com/en-us/library/fp161232.aspx)
- [Deploying and installing SharePoint Add-ins: methods and options](https://msdn.microsoft.com/en-us/library/office/fp179933.aspx)

**Comment by s-KaiNet** [comment]
@popeye669 
Is your issue resolved?
